services:
  php:
    image: app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      #DATABASE_URL: mysql://${DATABASE_USER:-root}:${DATABASE_PASSWORD:-root}@${DATABASE_URL:-database}/${DATABASE_DB:-app}?serverVersion=mariadb-11.5.2
      DATABASE_URL: mysql://root:root@database/app?serverVersion=mariadb-11.5.2
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      APP_ENV: ${APP_ENV:-dev}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8000:80"
    links:
        - database
    depends_on:
        - database

  database:
      image: mariadb
      environment:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: app
      volumes:
          - database_data:/var/lib/mysql/
          - ./database_data:/var/lib/mysql
          - ./.docker/database/scripts/reset:/usr/local/bin/reset
          - ./.docker/database/scripts/save:/usr/local/bin/save
      ports:
          - "3307:3306"

  # Node
  node:
    image: app-node
    build: .docker/node
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    volumes:
      - ./:/app:delegated
      - ${PNPM_STORE}:/app/.pnpm-store
    working_dir: /app
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  database_data:
  caddy_data:
  caddy_config:
