name: Build and Release Static Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

  build:
    name: Build and Release
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # PHP and Composer setup
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate

      # Node and Yarn asset build
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS dependencies and build assets
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Package built assets
        run: |
          mkdir -p release
          zip -r release/assets-builded.zip public/build

      # Optional: upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: release/

      # GitHub Release creation with assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          files: |
            ./release/assets-builded.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
